In [1]:
import matplotlib.pyplot as plt
import numpy as np
import math
import pandas as pd 
letters = {}

for i in range(9,99):
    letters[str(i+1)] = 0
    

nfib = 500

In [2]:
df = pd.read_csv("https://docs.google.com/spreadsheets/d/1ucG1-hX98WhlsNOkqBAoqpj3WNPcF0dc/export?format=csv")
df

      PL     PN  LIBRE-PINU  TOTAL
0   6112  16850       15339  38531
1    886   5786        3291  10023
2   3902  13914       18715  36778
3    508   2314        1602   4458
4   1776   4875        4665  11392
5     52   1528        1421   3029
6   1158   1454        1155   3814
7   1423   3997        2532   7995
8    698   1918        1548   4194
9    621   2990        1870   5514
10    83   2178        3026   5319
11   722   1568        1170   3496
12   516   1684        1620   3876
13   107   1701        1424   3328
14   254   2228        2615   5124
15   271   2242        1564   4093
16  1766   3957        3366   9167
17  1071   2963        1210   5275
18   481   4523        3504   8557
19   207   2226        2888   5345
20   183   2171        2240   4613
21   753   2218        1629   4668
22  2596   5482        3383  11828

In [3]:
pl = []
for i in df['PL']:
    pl.append(i)
pl

[6112,
 886,
 3902,
 508,
 1776,
 52,
 1158,
 1423,
 698,
 621,
 83,
 722,
 516,
 107,
 254,
 271,
 1766,
 1071,
 481,
 207,
 183,
 753,
 2596]

In [4]:
pn = []
for i in df['PN']:
    pn.append(i)
pn

[16850,
 5786,
 13914,
 2314,
 4875,
 1528,
 1454,
 3997,
 1918,
 2990,
 2178,
 1568,
 1684,
 1701,
 2228,
 2242,
 3957,
 2963,
 4523,
 2226,
 2171,
 2218,
 5482]

In [5]:
pli = []
for i in df['LIBRE-PINU']:
    pli.append(i)
pli

[15339,
 3291,
 18715,
 1602,
 4665,
 1421,
 1155,
 2532,
 1548,
 1870,
 3026,
 1170,
 1620,
 1424,
 2615,
 1564,
 3366,
 1210,
 3504,
 2888,
 2240,
 1629,
 3383]

In [6]:
tot = []
for i in df['TOTAL']:
    tot.append(i)
tot

[38531,
 10023,
 36778,
 4458,
 11392,
 3029,
 3814,
 7995,
 4194,
 5514,
 5319,
 3496,
 3876,
 3328,
 5124,
 4093,
 9167,
 5275,
 8557,
 5345,
 4613,
 4668,
 11828]

In [7]:
list_of_nums = pl
for n in list_of_nums:
    first_digit = str(n)[0]+str(n)[1]
    letters[first_digit] += 1
y = [round(val / nfib, 4) for val in letters.values()]
fre_relativa = y
y = list(letters.values())
f0= y
x = list(letters.keys())
y =  [round(math.log10(1+(1/int(val))), 4) for val in letters.keys()]
benford = y

In [8]:
f0 = np.array(f0)
f0

array([2, 1, 0, 0, 1, 0, 0, 2, 1, 0, 1, 0, 0, 0, 0, 2, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1,
       0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0])

In [9]:
fre_relativa = np.array(fre_relativa)
fre_relativa

array([0.004, 0.002, 0.   , 0.   , 0.002, 0.   , 0.   , 0.004, 0.002,
       0.   , 0.002, 0.   , 0.   , 0.   , 0.   , 0.004, 0.   , 0.002,
       0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   ,
       0.   , 0.   , 0.002, 0.   , 0.   , 0.   , 0.   , 0.   , 0.   ,
       0.   , 0.   , 0.002, 0.   , 0.002, 0.002, 0.002, 0.   , 0.   ,
       0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.002, 0.002, 0.   ,
       0.   , 0.   , 0.   , 0.   , 0.   , 0.002, 0.   , 0.   , 0.002,
       0.   , 0.   , 0.002, 0.   , 0.   , 0.   , 0.   , 0.   , 0.   ,
       0.   , 0.002, 0.   , 0.   , 0.   , 0.   , 0.002, 0.   , 0.   ,
       0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   ])

In [10]:
benford = np.array(benford)
benford

array([0.0414, 0.0378, 0.0348, 0.0322, 0.03  , 0.028 , 0.0263, 0.0248,
       0.0235, 0.0223, 0.0212, 0.0202, 0.0193, 0.0185, 0.0177, 0.017 ,
       0.0164, 0.0158, 0.0152, 0.0147, 0.0142, 0.0138, 0.0134, 0.013 ,
       0.0126, 0.0122, 0.0119, 0.0116, 0.0113, 0.011 , 0.0107, 0.0105,
       0.0102, 0.01  , 0.0098, 0.0095, 0.0093, 0.0091, 0.009 , 0.0088,
       0.0086, 0.0084, 0.0083, 0.0081, 0.008 , 0.0078, 0.0077, 0.0076,
       0.0074, 0.0073, 0.0072, 0.0071, 0.0069, 0.0068, 0.0067, 0.0066,
       0.0065, 0.0064, 0.0063, 0.0062, 0.0062, 0.0061, 0.006 , 0.0059,
       0.0058, 0.0058, 0.0057, 0.0056, 0.0055, 0.0055, 0.0054, 0.0053,
       0.0053, 0.0052, 0.0051, 0.0051, 0.005 , 0.005 , 0.0049, 0.0049,
       0.0048, 0.0047, 0.0047, 0.0046, 0.0046, 0.0045, 0.0045, 0.0045,
       0.0044, 0.0044])

In [11]:
f0_tot=f0.sum()
f0_tot

23

In [12]:
fe = benford*f0_tot

In [13]:
fe

array([0.9522, 0.8694, 0.8004, 0.7406, 0.69  , 0.644 , 0.6049, 0.5704,
       0.5405, 0.5129, 0.4876, 0.4646, 0.4439, 0.4255, 0.4071, 0.391 ,
       0.3772, 0.3634, 0.3496, 0.3381, 0.3266, 0.3174, 0.3082, 0.299 ,
       0.2898, 0.2806, 0.2737, 0.2668, 0.2599, 0.253 , 0.2461, 0.2415,
       0.2346, 0.23  , 0.2254, 0.2185, 0.2139, 0.2093, 0.207 , 0.2024,
       0.1978, 0.1932, 0.1909, 0.1863, 0.184 , 0.1794, 0.1771, 0.1748,
       0.1702, 0.1679, 0.1656, 0.1633, 0.1587, 0.1564, 0.1541, 0.1518,
       0.1495, 0.1472, 0.1449, 0.1426, 0.1426, 0.1403, 0.138 , 0.1357,
       0.1334, 0.1334, 0.1311, 0.1288, 0.1265, 0.1265, 0.1242, 0.1219,
       0.1219, 0.1196, 0.1173, 0.1173, 0.115 , 0.115 , 0.1127, 0.1127,
       0.1104, 0.1081, 0.1081, 0.1058, 0.1058, 0.1035, 0.1035, 0.1035,
       0.1012, 0.1012])

In [14]:
fe.sum()

22.9977

In [15]:
diferencia = fre_relativa - benford
diferencia

array([-0.0374, -0.0358, -0.0348, -0.0322, -0.028 , -0.028 , -0.0263,
       -0.0208, -0.0215, -0.0223, -0.0192, -0.0202, -0.0193, -0.0185,
       -0.0177, -0.013 , -0.0164, -0.0138, -0.0152, -0.0147, -0.0142,
       -0.0138, -0.0134, -0.013 , -0.0126, -0.0122, -0.0119, -0.0116,
       -0.0113, -0.009 , -0.0107, -0.0105, -0.0102, -0.01  , -0.0098,
       -0.0095, -0.0093, -0.0091, -0.007 , -0.0088, -0.0066, -0.0064,
       -0.0063, -0.0081, -0.008 , -0.0078, -0.0077, -0.0076, -0.0074,
       -0.0073, -0.0072, -0.0051, -0.0049, -0.0068, -0.0067, -0.0066,
       -0.0065, -0.0064, -0.0063, -0.0042, -0.0062, -0.0061, -0.004 ,
       -0.0059, -0.0058, -0.0038, -0.0057, -0.0056, -0.0055, -0.0055,
       -0.0054, -0.0053, -0.0053, -0.0032, -0.0051, -0.0051, -0.005 ,
       -0.005 , -0.0029, -0.0049, -0.0048, -0.0047, -0.0047, -0.0046,
       -0.0046, -0.0045, -0.0045, -0.0045, -0.0044, -0.0044])

In [16]:
diferencia.sum()

-0.9539

In [17]:
f0_fe= (f0-fe)

In [18]:
f0_fe_2 = f0_fe*f0_fe

In [19]:
f0_fe_2_fe=f0_fe_2/fe
f0_fe_2_fe

array([1.15299815, 0.01961854, 0.8004    , 0.7406    , 0.13927536,
       0.644     , 0.6049    , 3.58302272, 0.39063876, 0.5129    ,
       0.53846136, 0.4646    , 0.4439    , 0.4255    , 0.4071    ,
       6.62117903, 0.3772    , 1.11518866, 0.3496    , 0.3381    ,
       0.3266    , 0.3174    , 0.3082    , 0.299     , 0.2898    ,
       0.2806    , 0.2737    , 0.2668    , 0.2599    , 2.20556917,
       0.2461    , 0.2415    , 0.2346    , 0.23      , 0.2254    ,
       0.2185    , 0.2139    , 0.2093    , 3.03791787, 0.2024    ,
       3.25341173, 3.36918344, 3.42924468, 0.1863    , 0.184     ,
       0.1794    , 0.1771    , 0.1748    , 0.1702    , 0.1679    ,
       0.1656    , 4.28699871, 4.45989723, 0.1564    , 0.1541    ,
       0.1518    , 0.1495    , 0.1472    , 0.1449    , 5.15522272,
       0.1426    , 0.1403    , 5.38437681, 0.1357    , 0.1334    ,
       5.62965187, 0.1311    , 0.1288    , 0.1265    , 0.1265    ,
       0.1242    , 0.1219    , 0.1219    , 6.48080401, 0.1173    ,
       0.1173    , 0.115     , 0.115     , 6.98581446, 0.1127    ,
       0.1104    , 0.1081    , 0.1081    , 0.1058    , 0.1058    ,
       0.1035    , 0.1035    , 0.1035    , 0.1012    , 0.1012    ])

# Partido Liberal

In [20]:
x_2 = f0_fe_2_fe.sum()
x_2

83.3614753072456

In [21]:
letters = {}

for i in range(9,99):
    letters[str(i+1)] = 0
    
list_of_nums = pn
for n in list_of_nums:
    first_digit = str(n)[0]+str(n)[1]
    letters[first_digit] += 1
y = [round(val / nfib, 4) for val in letters.values()]
fre_relativa = y
y = list(letters.values())
f0= y
x = list(letters.keys())
y =  [round(math.log10(1+(1/int(val))), 4) for val in letters.keys()]
benford = y

In [22]:
f0 = np.array(f0)
f0

array([0, 0, 0, 1, 1, 2, 2, 1, 0, 1, 0, 2, 4, 1, 0, 0, 0, 0, 0, 2, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0,
       1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0])

In [23]:
fre_relativa = np.array(fre_relativa)
fre_relativa

array([0.   , 0.   , 0.   , 0.002, 0.002, 0.004, 0.004, 0.002, 0.   ,
       0.002, 0.   , 0.004, 0.008, 0.002, 0.   , 0.   , 0.   , 0.   ,
       0.   , 0.004, 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   ,
       0.   , 0.   , 0.004, 0.   , 0.   , 0.   , 0.   , 0.   , 0.002,
       0.   , 0.   , 0.002, 0.   , 0.   , 0.   , 0.   , 0.   , 0.002,
       0.   , 0.   , 0.002, 0.   , 0.   , 0.   , 0.   , 0.   , 0.   ,
       0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   ,
       0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   ,
       0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   ,
       0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   ])

In [24]:
benford = np.array(benford)
benford

array([0.0414, 0.0378, 0.0348, 0.0322, 0.03  , 0.028 , 0.0263, 0.0248,
       0.0235, 0.0223, 0.0212, 0.0202, 0.0193, 0.0185, 0.0177, 0.017 ,
       0.0164, 0.0158, 0.0152, 0.0147, 0.0142, 0.0138, 0.0134, 0.013 ,
       0.0126, 0.0122, 0.0119, 0.0116, 0.0113, 0.011 , 0.0107, 0.0105,
       0.0102, 0.01  , 0.0098, 0.0095, 0.0093, 0.0091, 0.009 , 0.0088,
       0.0086, 0.0084, 0.0083, 0.0081, 0.008 , 0.0078, 0.0077, 0.0076,
       0.0074, 0.0073, 0.0072, 0.0071, 0.0069, 0.0068, 0.0067, 0.0066,
       0.0065, 0.0064, 0.0063, 0.0062, 0.0062, 0.0061, 0.006 , 0.0059,
       0.0058, 0.0058, 0.0057, 0.0056, 0.0055, 0.0055, 0.0054, 0.0053,
       0.0053, 0.0052, 0.0051, 0.0051, 0.005 , 0.005 , 0.0049, 0.0049,
       0.0048, 0.0047, 0.0047, 0.0046, 0.0046, 0.0045, 0.0045, 0.0045,
       0.0044, 0.0044])

In [25]:
f0_tot=f0.sum()
f0_tot

23

In [26]:
fe = benford*f0_tot

In [27]:
fe

array([0.9522, 0.8694, 0.8004, 0.7406, 0.69  , 0.644 , 0.6049, 0.5704,
       0.5405, 0.5129, 0.4876, 0.4646, 0.4439, 0.4255, 0.4071, 0.391 ,
       0.3772, 0.3634, 0.3496, 0.3381, 0.3266, 0.3174, 0.3082, 0.299 ,
       0.2898, 0.2806, 0.2737, 0.2668, 0.2599, 0.253 , 0.2461, 0.2415,
       0.2346, 0.23  , 0.2254, 0.2185, 0.2139, 0.2093, 0.207 , 0.2024,
       0.1978, 0.1932, 0.1909, 0.1863, 0.184 , 0.1794, 0.1771, 0.1748,
       0.1702, 0.1679, 0.1656, 0.1633, 0.1587, 0.1564, 0.1541, 0.1518,
       0.1495, 0.1472, 0.1449, 0.1426, 0.1426, 0.1403, 0.138 , 0.1357,
       0.1334, 0.1334, 0.1311, 0.1288, 0.1265, 0.1265, 0.1242, 0.1219,
       0.1219, 0.1196, 0.1173, 0.1173, 0.115 , 0.115 , 0.1127, 0.1127,
       0.1104, 0.1081, 0.1081, 0.1058, 0.1058, 0.1035, 0.1035, 0.1035,
       0.1012, 0.1012])

In [28]:
fe.sum()

22.9977

In [29]:
diferencia = fre_relativa - benford
diferencia

array([-0.0414, -0.0378, -0.0348, -0.0302, -0.028 , -0.024 , -0.0223,
       -0.0228, -0.0235, -0.0203, -0.0212, -0.0162, -0.0113, -0.0165,
       -0.0177, -0.017 , -0.0164, -0.0158, -0.0152, -0.0107, -0.0142,
       -0.0138, -0.0134, -0.013 , -0.0126, -0.0122, -0.0119, -0.0116,
       -0.0113, -0.007 , -0.0107, -0.0105, -0.0102, -0.01  , -0.0098,
       -0.0075, -0.0093, -0.0091, -0.007 , -0.0088, -0.0086, -0.0084,
       -0.0083, -0.0081, -0.006 , -0.0078, -0.0077, -0.0056, -0.0074,
       -0.0073, -0.0072, -0.0071, -0.0069, -0.0068, -0.0067, -0.0066,
       -0.0065, -0.0064, -0.0063, -0.0062, -0.0062, -0.0061, -0.006 ,
       -0.0059, -0.0058, -0.0058, -0.0057, -0.0056, -0.0055, -0.0055,
       -0.0054, -0.0053, -0.0053, -0.0052, -0.0051, -0.0051, -0.005 ,
       -0.005 , -0.0049, -0.0049, -0.0048, -0.0047, -0.0047, -0.0046,
       -0.0046, -0.0045, -0.0045, -0.0045, -0.0044, -0.0044])

In [30]:
diferencia.sum()

-0.9539

In [31]:
f0_fe= (f0-fe)

In [32]:
f0_fe_2 = f0_fe*f0_fe

In [33]:
f0_fe_2_fe=f0_fe_2/fe
f0_fe_2_fe

array([ 0.9522    ,  0.8694    ,  0.8004    ,  0.09085655,  0.13927536,
        2.85518012,  3.21756325,  0.32355568,  0.5405    ,  0.4625978 ,
        0.4876    ,  5.07415661, 28.48805409,  0.77567626,  0.4071    ,
        0.391     ,  0.3772    ,  0.3634    ,  0.3496    ,  8.16891928,
        0.3266    ,  0.3174    ,  0.3082    ,  0.299     ,  0.2898    ,
        0.2806    ,  0.2737    ,  0.2668    ,  0.2599    , 12.06327668,
        0.2461    ,  0.2415    ,  0.2346    ,  0.23      ,  0.2254    ,
        2.79515904,  0.2139    ,  0.2093    ,  3.03791787,  0.2024    ,
        0.1978    ,  0.1932    ,  0.1909    ,  0.1863    ,  3.61878261,
        0.1794    ,  0.1771    ,  3.8956238 ,  0.1702    ,  0.1679    ,
        0.1656    ,  0.1633    ,  0.1587    ,  0.1564    ,  0.1541    ,
        0.1518    ,  0.1495    ,  0.1472    ,  0.1449    ,  0.1426    ,
        0.1426    ,  0.1403    ,  0.138     ,  0.1357    ,  0.1334    ,
        0.1334    ,  0.1311    ,  0.1288    ,  0.1265    ,  0.1265    ,
        0.1242    ,  0.1219    ,  0.1219    ,  0.1196    ,  0.1173    ,
        0.1173    ,  0.115     ,  0.115     ,  0.1127    ,  0.1127    ,
        0.1104    ,  0.1081    ,  0.1081    ,  0.1058    ,  0.1058    ,
        0.1035    ,  0.1035    ,  0.1035    ,  0.1012    ,  0.1012    ])

# Partido Nacional

In [34]:
x_2 = f0_fe_2_fe.sum()
x_2

91.53209500698748

In [35]:
letters = {}

for i in range(9,99):
    letters[str(i+1)] = 0
    
list_of_nums = pli
for n in list_of_nums:
    first_digit = str(n)[0]+str(n)[1]
    letters[first_digit] += 1
y = [round(val / nfib, 4) for val in letters.values()]
fre_relativa = y
y = list(letters.values())
f0= y
x = list(letters.keys())
y =  [round(math.log10(1+(1/int(val))), 4) for val in letters.keys()]
benford = y

In [36]:
f0 = np.array(f0)
f0

array([0, 2, 1, 0, 2, 3, 3, 0, 2, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 1, 0,
       1, 2, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0])

In [37]:
fre_relativa = np.array(fre_relativa)
fre_relativa

array([0.   , 0.004, 0.002, 0.   , 0.004, 0.006, 0.006, 0.   , 0.004,
       0.   , 0.   , 0.   , 0.002, 0.   , 0.   , 0.002, 0.002, 0.   ,
       0.002, 0.   , 0.002, 0.   , 0.002, 0.004, 0.   , 0.002, 0.   ,
       0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   ,
       0.002, 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   ,
       0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   ,
       0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   ,
       0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   ,
       0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   ,
       0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   ])

In [38]:
benford = np.array(benford)
benford

array([0.0414, 0.0378, 0.0348, 0.0322, 0.03  , 0.028 , 0.0263, 0.0248,
       0.0235, 0.0223, 0.0212, 0.0202, 0.0193, 0.0185, 0.0177, 0.017 ,
       0.0164, 0.0158, 0.0152, 0.0147, 0.0142, 0.0138, 0.0134, 0.013 ,
       0.0126, 0.0122, 0.0119, 0.0116, 0.0113, 0.011 , 0.0107, 0.0105,
       0.0102, 0.01  , 0.0098, 0.0095, 0.0093, 0.0091, 0.009 , 0.0088,
       0.0086, 0.0084, 0.0083, 0.0081, 0.008 , 0.0078, 0.0077, 0.0076,
       0.0074, 0.0073, 0.0072, 0.0071, 0.0069, 0.0068, 0.0067, 0.0066,
       0.0065, 0.0064, 0.0063, 0.0062, 0.0062, 0.0061, 0.006 , 0.0059,
       0.0058, 0.0058, 0.0057, 0.0056, 0.0055, 0.0055, 0.0054, 0.0053,
       0.0053, 0.0052, 0.0051, 0.0051, 0.005 , 0.005 , 0.0049, 0.0049,
       0.0048, 0.0047, 0.0047, 0.0046, 0.0046, 0.0045, 0.0045, 0.0045,
       0.0044, 0.0044])

In [39]:
f0_tot=f0.sum()
f0_tot

23

In [40]:
fe = benford*f0_tot

In [41]:
fe

array([0.9522, 0.8694, 0.8004, 0.7406, 0.69  , 0.644 , 0.6049, 0.5704,
       0.5405, 0.5129, 0.4876, 0.4646, 0.4439, 0.4255, 0.4071, 0.391 ,
       0.3772, 0.3634, 0.3496, 0.3381, 0.3266, 0.3174, 0.3082, 0.299 ,
       0.2898, 0.2806, 0.2737, 0.2668, 0.2599, 0.253 , 0.2461, 0.2415,
       0.2346, 0.23  , 0.2254, 0.2185, 0.2139, 0.2093, 0.207 , 0.2024,
       0.1978, 0.1932, 0.1909, 0.1863, 0.184 , 0.1794, 0.1771, 0.1748,
       0.1702, 0.1679, 0.1656, 0.1633, 0.1587, 0.1564, 0.1541, 0.1518,
       0.1495, 0.1472, 0.1449, 0.1426, 0.1426, 0.1403, 0.138 , 0.1357,
       0.1334, 0.1334, 0.1311, 0.1288, 0.1265, 0.1265, 0.1242, 0.1219,
       0.1219, 0.1196, 0.1173, 0.1173, 0.115 , 0.115 , 0.1127, 0.1127,
       0.1104, 0.1081, 0.1081, 0.1058, 0.1058, 0.1035, 0.1035, 0.1035,
       0.1012, 0.1012])

In [42]:
fe.sum()

22.9977

In [43]:
diferencia = fre_relativa - benford
diferencia

array([-0.0414, -0.0338, -0.0328, -0.0322, -0.026 , -0.022 , -0.0203,
       -0.0248, -0.0195, -0.0223, -0.0212, -0.0202, -0.0173, -0.0185,
       -0.0177, -0.015 , -0.0144, -0.0158, -0.0132, -0.0147, -0.0122,
       -0.0138, -0.0114, -0.009 , -0.0126, -0.0102, -0.0119, -0.0116,
       -0.0113, -0.011 , -0.0107, -0.0105, -0.0102, -0.01  , -0.0098,
       -0.0095, -0.0073, -0.0091, -0.009 , -0.0088, -0.0086, -0.0084,
       -0.0083, -0.0081, -0.008 , -0.0078, -0.0077, -0.0076, -0.0074,
       -0.0073, -0.0072, -0.0071, -0.0069, -0.0068, -0.0067, -0.0066,
       -0.0065, -0.0064, -0.0063, -0.0062, -0.0062, -0.0061, -0.006 ,
       -0.0059, -0.0058, -0.0058, -0.0057, -0.0056, -0.0055, -0.0055,
       -0.0054, -0.0053, -0.0053, -0.0052, -0.0051, -0.0051, -0.005 ,
       -0.005 , -0.0049, -0.0049, -0.0048, -0.0047, -0.0047, -0.0046,
       -0.0046, -0.0045, -0.0045, -0.0045, -0.0044, -0.0044])

In [44]:
diferencia.sum()

-0.9539

In [45]:
f0_fe= (f0-fe)

In [46]:
f0_fe_2 = f0_fe*f0_fe

In [47]:
f0_fe_2_fe=f0_fe_2/fe
f0_fe_2_fe

array([0.9522    , 1.47027417, 0.04977531, 0.7406    , 2.48710145,
       8.61915528, 9.48339231, 0.5704    , 3.94105504, 0.5129    ,
       0.4876    , 0.4646    , 0.69665963, 0.4255    , 0.4071    ,
       0.94854476, 1.02831347, 0.3634    , 1.2100119 , 0.3381    ,
       1.38844936, 0.3174    , 1.55284633, 9.67692642, 0.2898    ,
       1.84439187, 0.2737    , 0.2668    , 0.2599    , 0.253     ,
       0.2461    , 0.2415    , 0.2346    , 0.23      , 0.2254    ,
       0.2185    , 2.88898181, 0.2093    , 0.207     , 0.2024    ,
       0.1978    , 0.1932    , 0.1909    , 0.1863    , 0.184     ,
       0.1794    , 0.1771    , 0.1748    , 0.1702    , 0.1679    ,
       0.1656    , 0.1633    , 0.1587    , 0.1564    , 0.1541    ,
       0.1518    , 0.1495    , 0.1472    , 0.1449    , 0.1426    ,
       0.1426    , 0.1403    , 0.138     , 0.1357    , 0.1334    ,
       0.1334    , 0.1311    , 0.1288    , 0.1265    , 0.1265    ,
       0.1242    , 0.1219    , 0.1219    , 0.1196    , 0.1173    ,
       0.1173    , 0.115     , 0.115     , 0.1127    , 0.1127    ,
       0.1104    , 0.1081    , 0.1081    , 0.1058    , 0.1058    ,
       0.1035    , 0.1035    , 0.1035    , 0.1012    , 0.1012    ])

# Partido Libre

In [48]:
x_2 = f0_fe_2_fe.sum()
x_2

63.14437911662377

In [49]:
letters = {}

for i in range(9,99):
    letters[str(i+1)] = 0
    
list_of_nums = tot
for n in list_of_nums:
    first_digit = str(n)[0]+str(n)[1]
    letters[first_digit] += 1
y = [round(val / nfib, 4) for val in letters.values()]
fre_relativa = y
y = list(letters.values())
f0= y
x = list(letters.keys())
y =  [round(math.log10(1+(1/int(val))), 4) for val in letters.keys()]
benford = y

In [50]:
f0 = np.array(f0)
f0

array([1, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0,
       0, 1, 1, 0, 1, 0, 3, 0, 1, 1, 0, 0, 1, 0, 2, 0, 0, 0, 0, 1, 1, 2,
       0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0])

In [51]:
fre_relativa = np.array(fre_relativa)
fre_relativa

array([0.002, 0.004, 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   ,
       0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   ,
       0.   , 0.   , 0.002, 0.   , 0.   , 0.002, 0.002, 0.   , 0.002,
       0.   , 0.006, 0.   , 0.002, 0.002, 0.   , 0.   , 0.002, 0.   ,
       0.004, 0.   , 0.   , 0.   , 0.   , 0.002, 0.002, 0.004, 0.   ,
       0.002, 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   ,
       0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   ,
       0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.002, 0.   , 0.   ,
       0.   , 0.   , 0.   , 0.002, 0.   , 0.   , 0.   , 0.   , 0.   ,
       0.002, 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   ])

In [52]:
benford = np.array(benford)
benford

array([0.0414, 0.0378, 0.0348, 0.0322, 0.03  , 0.028 , 0.0263, 0.0248,
       0.0235, 0.0223, 0.0212, 0.0202, 0.0193, 0.0185, 0.0177, 0.017 ,
       0.0164, 0.0158, 0.0152, 0.0147, 0.0142, 0.0138, 0.0134, 0.013 ,
       0.0126, 0.0122, 0.0119, 0.0116, 0.0113, 0.011 , 0.0107, 0.0105,
       0.0102, 0.01  , 0.0098, 0.0095, 0.0093, 0.0091, 0.009 , 0.0088,
       0.0086, 0.0084, 0.0083, 0.0081, 0.008 , 0.0078, 0.0077, 0.0076,
       0.0074, 0.0073, 0.0072, 0.0071, 0.0069, 0.0068, 0.0067, 0.0066,
       0.0065, 0.0064, 0.0063, 0.0062, 0.0062, 0.0061, 0.006 , 0.0059,
       0.0058, 0.0058, 0.0057, 0.0056, 0.0055, 0.0055, 0.0054, 0.0053,
       0.0053, 0.0052, 0.0051, 0.0051, 0.005 , 0.005 , 0.0049, 0.0049,
       0.0048, 0.0047, 0.0047, 0.0046, 0.0046, 0.0045, 0.0045, 0.0045,
       0.0044, 0.0044])

In [53]:
f0_tot=f0.sum()
f0_tot

23

In [54]:
fe = benford*f0_tot

In [55]:
fe

array([0.9522, 0.8694, 0.8004, 0.7406, 0.69  , 0.644 , 0.6049, 0.5704,
       0.5405, 0.5129, 0.4876, 0.4646, 0.4439, 0.4255, 0.4071, 0.391 ,
       0.3772, 0.3634, 0.3496, 0.3381, 0.3266, 0.3174, 0.3082, 0.299 ,
       0.2898, 0.2806, 0.2737, 0.2668, 0.2599, 0.253 , 0.2461, 0.2415,
       0.2346, 0.23  , 0.2254, 0.2185, 0.2139, 0.2093, 0.207 , 0.2024,
       0.1978, 0.1932, 0.1909, 0.1863, 0.184 , 0.1794, 0.1771, 0.1748,
       0.1702, 0.1679, 0.1656, 0.1633, 0.1587, 0.1564, 0.1541, 0.1518,
       0.1495, 0.1472, 0.1449, 0.1426, 0.1426, 0.1403, 0.138 , 0.1357,
       0.1334, 0.1334, 0.1311, 0.1288, 0.1265, 0.1265, 0.1242, 0.1219,
       0.1219, 0.1196, 0.1173, 0.1173, 0.115 , 0.115 , 0.1127, 0.1127,
       0.1104, 0.1081, 0.1081, 0.1058, 0.1058, 0.1035, 0.1035, 0.1035,
       0.1012, 0.1012])

In [56]:
fe.sum()

22.9977

In [57]:
diferencia = fre_relativa - benford
diferencia

array([-0.0394, -0.0338, -0.0348, -0.0322, -0.03  , -0.028 , -0.0263,
       -0.0248, -0.0235, -0.0223, -0.0212, -0.0202, -0.0193, -0.0185,
       -0.0177, -0.017 , -0.0164, -0.0158, -0.0152, -0.0147, -0.0122,
       -0.0138, -0.0134, -0.011 , -0.0106, -0.0122, -0.0099, -0.0116,
       -0.0053, -0.011 , -0.0087, -0.0085, -0.0102, -0.01  , -0.0078,
       -0.0095, -0.0053, -0.0091, -0.009 , -0.0088, -0.0086, -0.0064,
       -0.0063, -0.0041, -0.008 , -0.0058, -0.0077, -0.0076, -0.0074,
       -0.0073, -0.0072, -0.0071, -0.0069, -0.0068, -0.0067, -0.0066,
       -0.0065, -0.0064, -0.0063, -0.0062, -0.0062, -0.0061, -0.006 ,
       -0.0059, -0.0058, -0.0058, -0.0057, -0.0056, -0.0055, -0.0035,
       -0.0054, -0.0053, -0.0053, -0.0052, -0.0051, -0.0031, -0.005 ,
       -0.005 , -0.0049, -0.0049, -0.0048, -0.0027, -0.0047, -0.0046,
       -0.0046, -0.0045, -0.0045, -0.0045, -0.0044, -0.0044])

In [58]:
diferencia.sum()

-0.9539

In [59]:
f0_fe= (f0-fe)

In [60]:
f0_fe_2 = f0_fe*f0_fe

In [61]:
f0_fe_2_fe=f0_fe_2/fe
f0_fe_2_fe

array([2.39953791e-03, 1.47027417e+00, 8.00400000e-01, 7.40600000e-01,
       6.90000000e-01, 6.44000000e-01, 6.04900000e-01, 5.70400000e-01,
       5.40500000e-01, 5.12900000e-01, 4.87600000e-01, 4.64600000e-01,
       4.43900000e-01, 4.25500000e-01, 4.07100000e-01, 3.91000000e-01,
       3.77200000e-01, 3.63400000e-01, 3.49600000e-01, 3.38100000e-01,
       1.38844936e+00, 3.17400000e-01, 3.08200000e-01, 1.64348161e+00,
       1.74045562e+00, 2.80600000e-01, 1.92733537e+00, 2.66800000e-01,
       2.88886033e+01, 2.53000000e-01, 2.30948887e+00, 2.38228675e+00,
       2.34600000e-01, 2.30000000e-01, 2.66195723e+00, 2.18500000e-01,
       1.49142273e+01, 2.09300000e-01, 2.07000000e-01, 2.02400000e-01,
       1.97800000e-01, 3.36918344e+00, 3.42924468e+00, 1.76570461e+01,
       1.84000000e-01, 3.75353601e+00, 1.77100000e-01, 1.74800000e-01,
       1.70200000e-01, 1.67900000e-01, 1.65600000e-01, 1.63300000e-01,
       1.58700000e-01, 1.56400000e-01, 1.54100000e-01, 1.51800000e-01,
       1.49500000e-01, 1.47200000e-01, 1.44900000e-01, 1.42600000e-01,
       1.42600000e-01, 1.40300000e-01, 1.38000000e-01, 1.35700000e-01,
       1.33400000e-01, 1.33400000e-01, 1.31100000e-01, 1.28800000e-01,
       1.26500000e-01, 6.03163834e+00, 1.24200000e-01, 1.21900000e-01,
       1.21900000e-01, 1.19600000e-01, 1.17300000e-01, 6.64244919e+00,
       1.15000000e-01, 1.15000000e-01, 1.12700000e-01, 1.12700000e-01,
       1.10400000e-01, 7.35879380e+00, 1.08100000e-01, 1.05800000e-01,
       1.05800000e-01, 1.03500000e-01, 1.03500000e-01, 1.03500000e-01,
       1.01200000e-01, 1.01200000e-01])

# Total

In [62]:
x_2 = f0_fe_2_fe.sum()
x_2

125.26935067802506